# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sherlock-python',
                'doc_host': 'https://flintlabsai.github.io',
                'git_url': 'https://github.com/flintlabsai/sherlock-python',
                'lib_path': 'sherlock_python'},
  'syms': {'sherlock_python.core': {'sherlock_python.core.foo': ('core.html#foo', 'sherlock_python/core.py')}}}
